version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - nestjs_multi_db_postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  redis:
    image: redis:7-alpine
    container_name: nestjs-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - nestjs_multi_db_redis_data:/data
    networks:
      - nestjs-network

  mongodb:
    image: mongo:7
    container_name: nestjs-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: nestjs_logs
    ports:
      - '27017:27017'
    volumes:
      - nestjs_multi_db_mongodb_data:/data/db
    networks:
      - nestjs-network

  # Optional: Admin interfaces
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nestjs-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - nestjs_multi_db_pgadmin_data:/var/lib/pgadmin
    networks:
      - nestjs-network
    depends_on:
      - postgres

  mongo-express:
    image: mongo-express:latest
    container_name: nestjs-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - '8081:8081'
    networks:
      - nestjs-network
    depends_on:
      - mongodb

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nestjs-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - '8082:8081'
    networks:
      - nestjs-network
    depends_on:
      - redis

volumes:
  nestjs_multi_db_postgres_data:
  nestjs_multi_db_redis_data:
  nestjs_multi_db_mongodb_data:
  nestjs_multi_db_pgadmin_data:

networks:
  nestjs-network:
    driver: bridge
